version: '3.9'

services:
    nginx:
        image: nginx:latest
        ports:
          - '80:80'
          - '443:443'
        volumes:
          - ./html:/var/www/html
          - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
            #- /home/user1/prv/ssl-certs-from-zerossl-20240317/certificate-all.crt:/etc/cert/ssl-certs-from-zerossl-20240317/certificate-all.crt
            #- /home/user1/prv/ssl-certs-from-zerossl-20240317/private.key:/etc/cert/ssl-certs-from-zerossl-20240317/private.key
          - /var/log/nginx:/var/log/nginx
        environment:
          TZ: Asia/Seoul

    php-fpm:
        #image: php:7-fpm
        image: php:7-fpm-for-moniwiki
        volumes:
          - ./html:/var/www/html
          - ./php-fpm-conf-add.ini:/usr/local/etc/php/conf.d/php-fpm-conf-add.ini
        environment:
          TZ: Asia/Seoul

